spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/crate
    username: crate
    password: crate
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
    


                                                                                                                                                                          
management:                                                                                                                                                             
  endpoint:                               
    health:                                                                                                                                                             
      show-details: always
